import type { Metadata } from "next";
import { Maven_Pro } from "next/font/google";
import { Source_Serif_4 } from "next/font/google";
import "./globals.css";

const maven_pro = Maven_Pro({
  subsets: ["latin"],
  variable: "--font-maven-pro",
  display: "swap",
});
const source_serif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-source-serif",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bumper Pass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${maven_pro.variable} ${source_serif.variable}`}>
      <body>{children}</body>
    </html>
  );
}
